[build]
  publish = "client"
  command = "cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  SERVER_URL = "https://your-render-app.onrender.com"

[context.deploy-preview.environment]
  SERVER_URL = "https://your-render-app.onrender.com"